export default [
    {
        name: '1 Page Website',
        image: 'images/server-1.png',
        lineOne: 'Irish Servers',
        lineTwo: '1 Database',
        lineThree: '1 Email Address',
        lineFour: '5GB Storage',
        lineFive: '200GB Bandwidth',
        lineSix: 'Free Tier Support',
        cost: '€5/m',
    },
    {
        name: '5 Page Website',
        image: 'images/server-2.png',
        lineOne: 'Irish Servers',
        lineTwo: '5 Databases',
        lineThree: '5 Email Addresses',
        lineFour: '25GB Storage',
        lineFive: '1000GB Bandwidth',
        lineSix: 'Free Tier Support',
        cost: '€15/m',
    },
    {
        name: '25 Page Website',
        image: 'images/server-3.png',
        lineOne: 'Irish Servers',
        lineTwo: '100 Databases',
        lineThree: 'Unlimited Email Addresses',
        lineFour: '100GB Storage',
        lineFive: 'Unlimited Bandwidth',
        lineSix: 'Premium Tier Support',
        cost: '€25/m',
    },
    {
        name: '50 Page Website',
        image: 'images/server-4.png',
        lineOne: 'Irish Servers',
        lineTwo: 'Unlimited Databases',
        lineThree: 'Unlimited Email Addresses',
        lineFour: 'Unlimited Storage',
        lineFive: 'Unlimited Bandwidth',
        lineSix: 'Premium Tier Support',
        cost: '€50/m',
    }
]